In [1]:
import pandas as pd

In [2]:
file = pd.read_csv('arrests.csv')

In [3]:
file.head()

,Border,Sector,State/Territory,2000 (All Illegal Immigrants),2000 (Mexicans Only),2001 (All Illegal Immigrants),2001 (Mexicans Only),2002 (All Illegal Immigrants),2002 (Mexicans Only),2003 (All Illegal Immigrants),...,2012 (All Illegal Immigrants),2012 (Mexicans Only),2013 (All Illegal Immigrants),2013 (Mexicans Only),2014 (All Illegal Immigrants),2014 (Mexicans Only),2015 (All Illegal Immigrants),2015 (Mexicans Only),2016 (All Illegal Immigrants),2016 (Mexicans Only)
0,Coast,Livermore,CA,6205,6034,5211,5007,4371,4186,3565,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Coast,Miami,"FL, GA, SC, NC",6237,2421,5962,1590,5143,1825,5931,...,2509.0,831.0,1738.0,388.0,2034.0,277.0,1752.0,273.0,3205.0,652.0
2,Coast,New Orleans,"LA, AL, MS, FL",6478,5985,5033,4616,4665,4126,5151,...,474.0,277.0,500.0,262.0,950.0,465.0,849.0,394.0,764.0,388.0
3,Coast,Ramey,PR,1731,0,1952,0,835,0,1688,...,702.0,0.0,924.0,3.0,958.0,0.0,557.0,1.0,694.0,0.0
4,Coast,All,"PR, LA, AL, MS, FL, GA, SC, NC",20651,14440,18158,11213,15014,10137,16335,...,3685.0,1108.0,3162.0,653.0,3942.0,742.0,3158.0,668.0,4663.0,1040.0

In [5]:
droppedcolumn = file.drop(file.columns[[3,4,5,6,7,8,9,10,11,12,13,14]] , axis=1)

In [6]:
droppedcolumn.head()

,Border,Sector,State/Territory,2006 (All Illegal Immigrants),2006 (Mexicans Only),2007 (All Illegal Immigrants),2007 (Mexicans Only),2008 (All Illegal Immigrants),2008 (Mexicans Only),2009 (All Illegal Immigrants),...,2012 (All Illegal Immigrants),2012 (Mexicans Only),2013 (All Illegal Immigrants),2013 (Mexicans Only),2014 (All Illegal Immigrants),2014 (Mexicans Only),2015 (All Illegal Immigrants),2015 (Mexicans Only),2016 (All Illegal Immigrants),2016 (Mexicans Only)
0,Coast,Livermore,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Coast,Miami,"FL, GA, SC, NC",6032.0,1616.0,7120.0,1612.0,6020.0,1564.0,4425.0,...,2509.0,831.0,1738.0,388.0,2034.0,277.0,1752.0,273.0,3205.0,652.0
2,Coast,New Orleans,"LA, AL, MS, FL",3053.0,1840.0,4018.0,2633.0,4303.0,2923.0,3527.0,...,474.0,277.0,500.0,262.0,950.0,465.0,849.0,394.0,764.0,388.0
3,Coast,Ramey,PR,1436.0,2.0,548.0,0.0,572.0,0.0,418.0,...,702.0,0.0,924.0,3.0,958.0,0.0,557.0,1.0,694.0,0.0
4,Coast,All,"PR, LA, AL, MS, FL, GA, SC, NC",10521.0,3458.0,11686.0,4245.0,10895.0,4487.0,8370.0,...,3685.0,1108.0,3162.0,653.0,3942.0,742.0,3158.0,668.0,4663.0,1040.0

In [7]:
missingrows = droppedcolumn.dropna()

In [8]:
missingrows.head()

,Border,Sector,State/Territory,2006 (All Illegal Immigrants),2006 (Mexicans Only),2007 (All Illegal Immigrants),2007 (Mexicans Only),2008 (All Illegal Immigrants),2008 (Mexicans Only),2009 (All Illegal Immigrants),...,2012 (All Illegal Immigrants),2012 (Mexicans Only),2013 (All Illegal Immigrants),2013 (Mexicans Only),2014 (All Illegal Immigrants),2014 (Mexicans Only),2015 (All Illegal Immigrants),2015 (Mexicans Only),2016 (All Illegal Immigrants),2016 (Mexicans Only)
1,Coast,Miami,"FL, GA, SC, NC",6032.0,1616.0,7120.0,1612.0,6020.0,1564.0,4425.0,...,2509.0,831.0,1738.0,388.0,2034.0,277.0,1752.0,273.0,3205.0,652.0
2,Coast,New Orleans,"LA, AL, MS, FL",3053.0,1840.0,4018.0,2633.0,4303.0,2923.0,3527.0,...,474.0,277.0,500.0,262.0,950.0,465.0,849.0,394.0,764.0,388.0
3,Coast,Ramey,PR,1436.0,2.0,548.0,0.0,572.0,0.0,418.0,...,702.0,0.0,924.0,3.0,958.0,0.0,557.0,1.0,694.0,0.0
4,Coast,All,"PR, LA, AL, MS, FL, GA, SC, NC",10521.0,3458.0,11686.0,4245.0,10895.0,4487.0,8370.0,...,3685.0,1108.0,3162.0,653.0,3942.0,742.0,3158.0,668.0,4663.0,1040.0
5,North,Blaine,"WA, OR",811.0,485.0,749.0,518.0,954.0,643.0,843.0,...,537.0,270.0,360.0,106.0,272.0,58.0,282.0,67.0,271.0,40.0

In [9]:
missingrows

,Border,Sector,State/Territory,2006 (All Illegal Immigrants),2006 (Mexicans Only),2007 (All Illegal Immigrants),2007 (Mexicans Only),2008 (All Illegal Immigrants),2008 (Mexicans Only),2009 (All Illegal Immigrants),...,2012 (All Illegal Immigrants),2012 (Mexicans Only),2013 (All Illegal Immigrants),2013 (Mexicans Only),2014 (All Illegal Immigrants),2014 (Mexicans Only),2015 (All Illegal Immigrants),2015 (Mexicans Only),2016 (All Illegal Immigrants),2016 (Mexicans Only)
1,Coast,Miami,"FL, GA, SC, NC",6032.0,1616.0,7120.0,1612.0,6020.0,1564.0,4425.0,...,2509.0,831.0,1738.0,388.0,2034.0,277.0,1752.0,273.0,3205.0,652.0
2,Coast,New Orleans,"LA, AL, MS, FL",3053.0,1840.0,4018.0,2633.0,4303.0,2923.0,3527.0,...,474.0,277.0,500.0,262.0,950.0,465.0,849.0,394.0,764.0,388.0
3,Coast,Ramey,PR,1436.0,2.0,548.0,0.0,572.0,0.0,418.0,...,702.0,0.0,924.0,3.0,958.0,0.0,557.0,1.0,694.0,0.0
4,Coast,All,"PR, LA, AL, MS, FL, GA, SC, NC",10521.0,3458.0,11686.0,4245.0,10895.0,4487.0,8370.0,...,3685.0,1108.0,3162.0,653.0,3942.0,742.0,3158.0,668.0,4663.0,1040.0
5,North,Blaine,"WA, OR",811.0,485.0,749.0,518.0,954.0,643.0,843.0,...,537.0,270.0,360.0,106.0,272.0,58.0,282.0,67.0,271.0,40.0
6,North,Buffalo,"NY, PA",1517.0,959.0,2191.0,1271.0,3339.0,1618.0,2672.0,...,1143.0,607.0,796.0,370.0,741.0,294.0,291.0,137.0,226.0,82.0
7,North,Detroit,"OH, MI, IN, IL",1281.0,944.0,902.0,686.0,961.0,664.0,1157.0,...,950.0,673.0,650.0,479.0,647.0,431.0,637.0,427.0,716.0,504.0
8,North,Grand Forks,"WI, MN, ND",518.0,383.0,497.0,334.0,541.0,361.0,472.0,...,418.0,306.0,469.0,337.0,767.0,532.0,789.0,563.0,505.0,352.0
9,North,Havre,MT,568.0,511.0,486.0,409.0,427.0,379.0,283.0,...,102.0,54.0,88.0,62.0,91.0,51.0,64.0,46.0,43.0,12.0
10,North,Houlton,ME,175.0,58.0,95.0,17.0,81.0,12.0,59.0,...,41.0,8.0,37.0,1.0,45.0,5.0,32.0,1.0,25.0,7.0
11,North,Spokane,"MT, ID, WA",185.0,108.0,341.0,290.0,340.0,296.0,277.0,...,317.0,266.0,299.0,237.0,269.0,219.0,190.0,153.0,206.0,149.0
12,North,Swanton,"NH, VT, NY",1544.0,341.0,1119.0,284.0,1282.0,271.0,1043.0,...,702.0,122.0,531.0,80.0,506.0,75.0,341.0,43.0,291.0,23.0
13,North,All,"ME, NH, VT, NY, PA, OH, MI, IN, IL, WI, MN, ND...",6599.0,3789.0,6380.0,3809.0,7925.0,4244.0,6806.0,...,4210.0,2306.0,3230.0,1672.0,3338.0,1665.0,2626.0,1437.0,2283.0,1169.0
14,Southwest,Big Bend,TX,7520.0,6791.0,5536.0,5002.0,5391.0,4756.0,6360.0,...,3964.0,3417.0,3684.0,3174.0,4096.0,3164.0,5031.0,2177.0,6366.0,2728.0
15,Southwest,Del Rio,TX,42636.0,30361.0,22920.0,16286.0,20761.0,14916.0,17082.0,...,21720.0,12404.0,23510.0,14005.0,24255.0,10196.0,19013.0,10874.0,23078.0,12953.0
16,Southwest,El Centro,CA,61465.0,60723.0,55883.0,55271.0,40961.0,40159.0,33521.0,...,23916.0,22511.0,16306.0,15141.0,14511.0,12511.0,12820.0,11320.0,19448.0,14361.0
17,Southwest,El Paso,"NM, TX",122256.0,117532.0,75464.0,72293.0,30312.0,29137.0,14999.0,...,9678.0,8915.0,11154.0,10092.0,12339.0,9904.0,14495.0,10677.0,25634.0,13660.0
18,Southwest,Laredo,TX,74840.0,59146.0,56714.0,44831.0,43658.0,34403.0,40569.0,...,44872.0,31742.0,50749.0,32772.0,44049.0,26540.0,35888.0,25766.0,36562.0,25337.0
19,Southwest,Rio Grande Valley,TX,110528.0,58282.0,73430.0,51975.0,75473.0,55401.0,60989.0,...,97762.0,47823.0,154453.0,57624.0,256393.0,63468.0,147257.0,48173.0,186830.0,46334.0
20,Southwest,San Diego,CA,142104.0,140821.0,152460.0,151140.0,162390.0,160818.0,118721.0,...,28461.0,27307.0,27496.0,26223.0,29911.0,27871.0,26290.0,24269.0,31891.0,25380.0
21,Southwest,Tucson,AZ,392074.0,382610.0,378239.0,366456.0,317696.0,305429.0,241673.0,...,120000.0,102303.0,120939.0,101092.0,87915.0,68870.0,63397.0,48916.0,64891.0,46494.0
22,Southwest,Yuma,"CA, AZ",118549.0,117553.0,37992.0,37380.0,8363.0,8016.0,6951.0,...,6500.0,5919.0,6106.0,5286.0,5902.0,4247.0,7142.0,3845.0,14170.0,3513.0
23,Southwest,All,"CA, AZ, NM, TX",1071972.0,973819.0,858638.0,800634.0,705005.0,653035.0,540865.0,...,356873.0,262341.0,414397.0,265409.0,479371.0,226771.0,331333.0,186017.0,408870.0,190760.0

In [11]:
newdf = missingrows.drop(missingrows[missingrows.Sector == 'All'].index)

In [16]:
newdf.head()

,Border,Sector,State/Territory,2006 (All Illegal Immigrants),2006 (Mexicans Only),2007 (All Illegal Immigrants),2007 (Mexicans Only),2008 (All Illegal Immigrants),2008 (Mexicans Only),2009 (All Illegal Immigrants),...,2012 (All Illegal Immigrants),2012 (Mexicans Only),2013 (All Illegal Immigrants),2013 (Mexicans Only),2014 (All Illegal Immigrants),2014 (Mexicans Only),2015 (All Illegal Immigrants),2015 (Mexicans Only),2016 (All Illegal Immigrants),2016 (Mexicans Only)
1,Coast,Miami,"FL, GA, SC, NC",6032.0,1616.0,7120.0,1612.0,6020.0,1564.0,4425.0,...,2509.0,831.0,1738.0,388.0,2034.0,277.0,1752.0,273.0,3205.0,652.0
2,Coast,New Orleans,"LA, AL, MS, FL",3053.0,1840.0,4018.0,2633.0,4303.0,2923.0,3527.0,...,474.0,277.0,500.0,262.0,950.0,465.0,849.0,394.0,764.0,388.0
3,Coast,Ramey,PR,1436.0,2.0,548.0,0.0,572.0,0.0,418.0,...,702.0,0.0,924.0,3.0,958.0,0.0,557.0,1.0,694.0,0.0
5,North,Blaine,"WA, OR",811.0,485.0,749.0,518.0,954.0,643.0,843.0,...,537.0,270.0,360.0,106.0,272.0,58.0,282.0,67.0,271.0,40.0
6,North,Buffalo,"NY, PA",1517.0,959.0,2191.0,1271.0,3339.0,1618.0,2672.0,...,1143.0,607.0,796.0,370.0,741.0,294.0,291.0,137.0,226.0,82.0

In [19]:
formatted_df = pd.melt(newdf,
                       ("Border","Sector","State/Territory"),
                       var_name="Year & Type",
                       value_name="Arrests")
formatted_df.columns = ['Border', 'Sector', 'State/Territory', 'Year & Type', 'Arrests']
formatted_df.head()

  Border       Sector State/Territory                    Year & Type  Arrests
0  Coast        Miami  FL, GA, SC, NC  2006 (All Illegal Immigrants)   6032.0
1  Coast  New Orleans  LA, AL, MS, FL  2006 (All Illegal Immigrants)   3053.0
2  Coast        Ramey              PR  2006 (All Illegal Immigrants)   1436.0
3  North       Blaine          WA, OR  2006 (All Illegal Immigrants)    811.0
4  North      Buffalo          NY, PA  2006 (All Illegal Immigrants)   1517.0

In [20]:
split_year = formatted_df['Year & Type'].str[:-1].str.split('(', expand=True)

In [21]:
split_year.columns = ['Year', 'Type']

In [22]:
split_year.head()

    Year                    Type
0  2006   All Illegal Immigrants
1  2006   All Illegal Immigrants
2  2006   All Illegal Immigrants
3  2006   All Illegal Immigrants
4  2006   All Illegal Immigrants

In [23]:
concat = pd.concat([formatted_df, split_year], axis=1)

In [24]:
concat.head()

,Border,Sector,State/Territory,Year & Type,Arrests,Year,Type
0,Coast,Miami,"FL, GA, SC, NC",2006 (All Illegal Immigrants),6032.0,2006,All Illegal Immigrants
1,Coast,New Orleans,"LA, AL, MS, FL",2006 (All Illegal Immigrants),3053.0,2006,All Illegal Immigrants
2,Coast,Ramey,PR,2006 (All Illegal Immigrants),1436.0,2006,All Illegal Immigrants
3,North,Blaine,"WA, OR",2006 (All Illegal Immigrants),811.0,2006,All Illegal Immigrants
4,North,Buffalo,"NY, PA",2006 (All Illegal Immigrants),1517.0,2006,All Illegal Immigrants

In [26]:
concat.to_csv('final.csv')